### ISSUE TITLE
Handling end of line incase of variable declaration is numeric

### ISSUE THREAD

**Issue by birojnayak** [otterkit/otterkit-cobol#26] opened 2023-05-17 17:37 UTC
**Describe the bug**

<code>
01 Total    PIC 99 value 0.
</code>

When there is 0. , the parser should figure out the EOL and consider the initialization to just 0 instead of failing.

**To Reproduce**
[https://gist.github.com/birojnayak/4bd0d4332d98170f74803b3e217ca4f8](url)

**Expected behavior**
The parser shouldn't throw exception.

**Screenshots**
If applicable, add screenshots to help explain the issue. This could be terminal screenshots that can help us find the source of the issue.

**Platform Information (please complete the following information):**
 - OS: [e.g. Linux]
 - OS Version [e.g. Ubuntu 22.04]
 - CPU Architecture [e.g. x64]
 - Libotterkit Version [e.g. 1.0]

**Additional context**

**Comment by KTSnowy** [comment] 2023-05-17 19:15
Hey @birojnayak, I can't reproduce this issue anymore (with current commit).

It might be related to the previous figurative literal issue, the parser threw an exception because it wasn't able to parse the previous two lines:
```cobol
           01 Num1     PIC 9 values zeros.
           01 Num2     PIC 9 values zeros.
```

Both lines have figurative literals, after fixing the previous issue with them I don't get any exceptions during parsing with the code in the gist.

**Comment by birojnayak** [comment] 2023-05-17 21:16
Can you tag the PR which will close this issues ? something in this [line](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

**Comment by KTSnowy** [comment] 2023-05-17 21:19
Commit https://github.com/otterkit/otterkit/commit/e5a11a3322ea52cfebee647f15d630db6fbf67de fixes this issue. 

Manually closing the issue for now.

**Closed as completed by KTSnowy** 2023-05-17 21:19 UTC
